language: python
python:
  - "3.5"
services:
  - mysql
script: py.test -c pytest-travis.ini
install: 
  - pip install cython
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install coveralls
after_success:
  - coveralls
