language: python
python:
  - "3.5"
  - "3.6"
services:
  - mysql
  - redis-server
script: py.test -c pytest-travis.ini
install: 
  - pip install cython
  - pip install -r requirements.txt -r requirements-dev.txt --process-dependency-links
  - pip install coveralls
after_success:
  - coveralls
