version: "2"
services:
    mysql:
        image: mysql
        container_name: myreco-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: myreco_test
    redis:
        image: redis
        container_name: myreco-redis
    myreco:
        build: .
        image: myreco
        container_name: myreco
        stdin_open: true
        tty: true
        depends_on:
            - mysql
            - redis
        links:
            - mysql:myreco-mysql
            - redis:myreco-redis
        volumes:
            - $MYRECO_DEV_HOME:/myreco
