version: "2"
services:
    mysql:
        image: mysql
        container_name: myreco-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: myreco_test
        ports:
            - 3306:3306
    redis:
        image: redis
        container_name: myreco-redis
        ports:
            - 6379:6379
    elsearch:
        image: elasticsearch
        container_name: myreco-elsearch
        ports:
            - 9200:9200
